// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Projekat_Vezbe.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221102110334_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.NepoznataPtica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.HasKey("ID");

                    b.ToTable("NepoznataPtica");
                });

            modelBuilder.Entity("Models.Osobina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrednost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Osobina");
                });

            modelBuilder.Entity("Models.Podrucje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Podrucje");
                });

            modelBuilder.Entity("Models.Ptica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OsobinaID")
                        .HasColumnType("int");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OsobinaID");

                    b.ToTable("Ptica");
                });

            modelBuilder.Entity("Models.Vidjena", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BrojVidjenja")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("PodrucjeID")
                        .HasColumnType("int");

                    b.Property<int>("PticaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PodrucjeID");

                    b.HasIndex("PticaID");

                    b.ToTable("Vidjena");
                });

            modelBuilder.Entity("NepoznataPticaOsobina", b =>
                {
                    b.Property<int>("NepoznataID")
                        .HasColumnType("int");

                    b.Property<int>("OsobineID")
                        .HasColumnType("int");

                    b.HasKey("NepoznataID", "OsobineID");

                    b.HasIndex("OsobineID");

                    b.ToTable("NepoznataPticaOsobina");
                });

            modelBuilder.Entity("Models.Ptica", b =>
                {
                    b.HasOne("Models.Osobina", null)
                        .WithMany("Ptice")
                        .HasForeignKey("OsobinaID");
                });

            modelBuilder.Entity("Models.Vidjena", b =>
                {
                    b.HasOne("Models.Podrucje", "Podrucje")
                        .WithMany("Vidjena")
                        .HasForeignKey("PodrucjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Ptica", "Ptica")
                        .WithMany("Vidjena")
                        .HasForeignKey("PticaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podrucje");

                    b.Navigation("Ptica");
                });

            modelBuilder.Entity("NepoznataPticaOsobina", b =>
                {
                    b.HasOne("Models.NepoznataPtica", null)
                        .WithMany()
                        .HasForeignKey("NepoznataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Osobina", null)
                        .WithMany()
                        .HasForeignKey("OsobineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Osobina", b =>
                {
                    b.Navigation("Ptice");
                });

            modelBuilder.Entity("Models.Podrucje", b =>
                {
                    b.Navigation("Vidjena");
                });

            modelBuilder.Entity("Models.Ptica", b =>
                {
                    b.Navigation("Vidjena");
                });
#pragma warning restore 612, 618
        }
    }
}
